Create new endpoint to redact searched text
hmcts/em-native-pdf-annotator-app pull request #1291
Opened 2023-02-10 09:20 UTC by MichaelJacob21012

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EM-4869

### Change description ###
Create new endpoint to redact searched text

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-03-31 10:30 UTC, yogesh-hullatti requested changes

2023-03-31 10:30 UTC, yogesh-hullatti commented on src/aat/resources/application.yml
> +  search-markups: ${ENABLE_SEARCH_MARKUPS_ENDPOINT:true}
@MichaelJacob21012  - Could you set this to false? Let it by default be set to false.

2023-04-17 10:15 UTC, yogesh-hullatti approved these changes

2023-04-17 12:52 UTC, Ferdi-Cocelli approved these changes

2023-04-17 13:40 UTC, merged