CME-123: add db monitoring
hmcts/em-native-pdf-annotator-app pull request #2339
Opened 2024-12-05 13:21 UTC by AntonyLeons

### Jira link
https://tools.hmcts.net/jira/browse/CME-123

See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)

### Change description

### Testing done

### Checklist

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2024-12-09 09:43 UTC, kiran-yenigala-hmcts commented on infrastructure/main.tf
> +  action_group_name           = join("-", [local.db_name, var.action_group_name])
please format this block

2024-12-09 09:43 UTC, kiran-yenigala-hmcts requested changes
please format

2024-12-10 10:12 UTC, kiran-yenigala-hmcts approved these changes

2024-12-16 10:29 UTC, yogesh-hullatti approved these changes

2024-12-18 12:31 UTC, merged